/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_librealsense_Sensor */

#ifndef _Included_org_librealsense_Sensor
#define _Included_org_librealsense_Sensor
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_librealsense_Sensor
 * Method:    helloThere
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Sensor_helloThere
  (JNIEnv *, jobject);

/*
 * Class:     org_librealsense_Sensor
 * Method:    rs2CreateContext
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Sensor_rs2CreateContext
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
