/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_librealsense_Native */

#ifndef _Included_org_librealsense_Native
#define _Included_org_librealsense_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_librealsense_Native
 * Method:    helloThere
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_helloThere
  (JNIEnv *, jclass);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreateContext
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreateContext
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2QueryDevices
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2QueryDevices
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetDeviceCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2GetDeviceCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreateDevice
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreateDevice
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2SupportsDeviceInfo
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2SupportsDeviceInfo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetDeviceInfo
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_librealsense_Native_rs2GetDeviceInfo
  (JNIEnv *, jclass, jlong, jint);

#ifdef __cplusplus
}
#endif
#endif
