/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_librealsense_Native_Format */

#ifndef _Included_org_librealsense_Native_Format
#define _Included_org_librealsense_Native_Format
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
