/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_librealsense_Native_Extension */

#ifndef _Included_org_librealsense_Native_Extension
#define _Included_org_librealsense_Native_Extension
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
