/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class org_librealsense_Native */

#ifndef _Included_org_librealsense_Native
#define _Included_org_librealsense_Native
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreateContext
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreateContext
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DeleteContext
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2DeleteContext
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2QueryDevices
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2QueryDevices
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetDeviceCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2GetDeviceCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreateDevice
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreateDevice
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DeleteDevice
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2DeleteDevice
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2HardwareReset
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2HardwareReset
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2SupportsDeviceInfo
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2SupportsDeviceInfo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetDeviceInfo
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_librealsense_Native_rs2GetDeviceInfo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreatePipeline
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreatePipeline
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreateConfig
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreateConfig
  (JNIEnv *, jclass);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DeleteConfig
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2DeleteConfig
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2ConfigEnableStream
 * Signature: (JIIIIII)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2ConfigEnableStream
  (JNIEnv *, jclass, jlong, jint, jint, jint, jint, jint, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2ConfigEnableDevice
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2ConfigEnableDevice
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2ConfigEnableRecordToFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2ConfigEnableRecordToFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2ConfigEnableDeviceFromFile
 * Signature: (JLjava/lang/String;)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2ConfigEnableDeviceFromFile
  (JNIEnv *, jclass, jlong, jstring);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2ConfigDisableStream
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2ConfigDisableStream
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2ConfigCanResolve
 * Signature: (JJ)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2ConfigCanResolve
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PipelineStartWithConfig
 * Signature: (JJ)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2PipelineStartWithConfig
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PipelineStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2PipelineStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DeletePipeline
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2DeletePipeline
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PipelineProfileGetStreams
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2PipelineProfileGetStreams
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PipelineWaitForFrames
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2PipelineWaitForFrames
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PipelinePollForFrames
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2PipelinePollForFrames
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PipelineGetActiveProfile
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2PipelineGetActiveProfile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PipelineProfileGetDevice
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2PipelineProfileGetDevice
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PlaybackGetDuration
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2PlaybackGetDuration
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PlaybackSeek
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2PlaybackSeek
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PlaybackGetPosition
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2PlaybackGetPosition
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PlaybackDevicePause
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2PlaybackDevicePause
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PlaybackDeviceResume
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2PlaybackDeviceResume
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PlaybackDeviceStop
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2PlaybackDeviceStop
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PlaybackDeviceGetCurrentStatus
 * Signature: (J)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_librealsense_Native_rs2PlaybackDeviceGetCurrentStatus
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2EmbeddedFramesCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2EmbeddedFramesCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2ExtractFrame
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2ExtractFrame
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2ReleaseFrame
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2ReleaseFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetFrameNumber
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2GetFrameNumber
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetFrameStreamProfile
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2GetFrameStreamProfile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2IsFrameExtendableTo
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2IsFrameExtendableTo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetFrameWidth
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2GetFrameWidth
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetFrameHeight
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2GetFrameHeight
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetFrameStrideInBytes
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2GetFrameStrideInBytes
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DepthFrameGetDistance
 * Signature: (JII)F
 */
JNIEXPORT jfloat JNICALL Java_org_librealsense_Native_rs2DepthFrameGetDistance
  (JNIEnv *, jclass, jlong, jint, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetFrameData
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_librealsense_Native_rs2GetFrameData
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetFrameVertices
 * Signature: (J)Ljava/nio/ByteBuffer;
 */
JNIEXPORT jobject JNICALL Java_org_librealsense_Native_rs2GetFrameVertices
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2ExportToPly
 * Signature: (JLjava/lang/String;J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2ExportToPly
  (JNIEnv *, jclass, jlong, jstring, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2FrameAddRef
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2FrameAddRef
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2ProcessFrame
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2ProcessFrame
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2PollForFrame
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2PollForFrame
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreateFrameQueue
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreateFrameQueue
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2StartProcessingQueue
 * Signature: (JJ)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2StartProcessingQueue
  (JNIEnv *, jclass, jlong, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreateColorizer
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreateColorizer
  (JNIEnv *, jclass);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreatePointCloud
 * Signature: ()J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreatePointCloud
  (JNIEnv *, jclass);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreateAlign
 * Signature: (I)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreateAlign
  (JNIEnv *, jclass, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetFramePointsCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2GetFramePointsCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2QuerySensors
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2QuerySensors
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetSensorsCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2GetSensorsCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DeleteSensorList
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2DeleteSensorList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DeleteSensor
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2DeleteSensor
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2CreateSensor
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2CreateSensor
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetSensorInfo
 * Signature: (JI)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_org_librealsense_Native_rs2GetSensorInfo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2SupportsSensorInfo
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2SupportsSensorInfo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2IsSensorExtendableTo
 * Signature: (JI)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2IsSensorExtendableTo
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetDepthScale
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_librealsense_Native_rs2GetDepthScale
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DepthStereoFrameGetBaseline
 * Signature: (J)F
 */
JNIEXPORT jfloat JNICALL Java_org_librealsense_Native_rs2DepthStereoFrameGetBaseline
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetStreamProfiles
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2GetStreamProfiles
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetStreamProfileCount
 * Signature: (J)I
 */
JNIEXPORT jint JNICALL Java_org_librealsense_Native_rs2GetStreamProfileCount
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DeleteStreamProfilesList
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2DeleteStreamProfilesList
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetStreamProfile
 * Signature: (JI)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2GetStreamProfile
  (JNIEnv *, jclass, jlong, jint);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DeleteStreamProfile
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2DeleteStreamProfile
  (JNIEnv *, jclass, jlong);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetVideoStreamIntrinsics
 * Signature: (JLorg/librealsense/types/Intrinsics;)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2GetVideoStreamIntrinsics
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2GetStreamProfileData
 * Signature: (JLorg/librealsense/streamprofiles/StreamProfileData;)V
 */
JNIEXPORT void JNICALL Java_org_librealsense_Native_rs2GetStreamProfileData
  (JNIEnv *, jclass, jlong, jobject);

/*
 * Class:     org_librealsense_Native
 * Method:    rs2DeleteIntrinsics
 * Signature: (J)J
 */
JNIEXPORT jlong JNICALL Java_org_librealsense_Native_rs2DeleteIntrinsics
  (JNIEnv *, jclass, jlong);

#ifdef __cplusplus
}
#endif
#endif
